baseurl = "/"
languageCode = "fr-fr"
title = "Mon Nouveau Site Hugo"
theme = "hugo-strata-theme"
disqusShortname = "tof"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "votre nom"
	description = "Décrivez ici votre site web"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Je suis StrataDoc**, un modèle de site <br> gratuit <br> conçu par [HTML5 UP](//html5up.net)."
		# The icons will be shown if you enter your username
		twitter = "xtof_party"
		github = "ChristopheDucamp"
		gitlab = ""
		dribbble = ""
		facebook = "christophe.ducamp"
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; tof",
			"Design: [HTML5 UP](//html5up.net)",
			"Images démo: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Apprentissage d'Hugo et Netlify."
		content = "Découvertre du modèle "Victor Hugo" avec un thème Strata. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.portfolio]
		hide  = false
		title = "Photos Récentes"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Articles récents"

	[params.contact]
		hide  = false
		title = "On reste en contact"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nom"
			email = "e-mail"
			message = "Message"
			submit = "Envoyez-moi un message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Accueil"
	url  = "/"
	weight = 0

[[menu.main]]
    name = "À Propos"
    url = "a-propos"
    weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
